package github.jsonta.quiz;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.*;

public class PasswdResetFrame extends JPanel implements WindowListener {
    public PasswdResetFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        requestPwdRstBttn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Podaj adres e-mail użyty do rejestracji Twojego konta");

        requestPwdRstBttn.setText("Zresetuj hasło");
        requestPwdRstBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPwdRstBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTextField))
                    .addComponent(requestPwdRstBttn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestPwdRstBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestPwdRstBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPwdRstBttnActionPerformed
        PasswdResetThread thread;
        emailTextField.setEnabled(false);
        if (!emailTextField.getText().equals("")) {
            thread = new PasswdResetThread(emailTextField.getText());
            thread.start();
            try {
                thread.join();
            } catch (InterruptedException e) {}
            
            if (thread.didRequestSend()) {
                JOptionPane.showMessageDialog(null, "Żądanie resetowania hasła zostało wysłane. Sprawdź swoją skrzynkę odbiorczą.", "Komunikat", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Proszę podać adres e-mail przypisany do konta, którego hasło chcesz zresetować.", "Komunikat", JOptionPane.ERROR_MESSAGE);
        }
        emailTextField.setEnabled(true);
    }//GEN-LAST:event_requestPwdRstBttnActionPerformed
    
    @Override
    public void windowOpened(WindowEvent e) {
        JOptionPane.showMessageDialog(null, "Możliwość resetowania hasła nie została jeszcze zaimplementowana.", "Komunikat", JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void windowClosing(WindowEvent e) {}

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestPwdRstBttn;
    // End of variables declaration//GEN-END:variables
}
